
# URL per MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/submission

# Credenziali di accesso
spring.datasource.username=root
spring.datasource.password=Francesco.root_05

# ========= CONFIGURAZIONE HIBERNATE (JPA) =========
# 'update' è ok per lo sviluppo.
spring.jpa.hibernate.ddl-auto=update

# (Opzionale) Mostra le query SQL generate da Hibernate
spring.jpa.show-sql=true

spring.session.jdbc.initialize-schema=never
spring.session.store-type=none